Everything SA
amczuboka/Decagon-CondoManagementSystem pull request #136
Opened 2024-02-06 19:36 UTC by amczuboka

#135 Created 'documentation' folder where the SAD pdf as well as all the diagrams created by @KarinaSandur and @amczuboka is added.

2024-02-06 20:05 UTC, Guillaume-Lachapelle requested changes
I saw in the activity diagram for registration in your PR that register redirects to profile page, but in reality it actually redirects to "verify-email" page. Then the user verifies their email and they can go back to login page and log in, which redirects them to the landing page.

2024-02-06 20:33 UTC, Guillaume-Lachapelle approved these changes

2024-02-06 20:59 UTC, Ziadsharkos approved these changes

2024-02-06 21:12 UTC, CarlaShawi approved these changes

2024-02-06 21:19 UTC, Tharsipa approved these changes

2024-02-06 21:22 UTC, IsabelleCzuboka approved these changes
All good

2024-02-06 21:24 UTC, KarinaSandur approved these changes
All good!

2024-02-07 02:50 UTC, Holyvert approved these changes

2024-02-07 02:51 UTC, merged