Create & Style Condo Component
amczuboka/Decagon-CondoManagementSystem pull request #154
Opened 2024-02-26 18:11 UTC by IsabelleCzuboka

Co-Authored-By: amczuboka <94947740+amczuboka@users.noreply.github.com>

#41 Added condo component and styled it.  also added an attribute Style in the condo model.

This pull request is about the condo component, it is just a visual representation right now no back end. It is shown on the building-info page that Karina created in the condo section.

2024-02-26 18:13 UTC, Ziadsharkos approved these changes

2024-02-26 18:28 UTC, npiperni approved these changes

2024-02-26 18:29 UTC, Ziadsharkos approved these changes

2024-02-26 18:37 UTC, amczuboka approved these changes
Looks good, resizable as well

2024-02-27 00:58 UTC, KarinaSandur approved these changes

2024-02-27 23:39 UTC, PaulFarid approved these changes

2024-02-28 00:52 UTC, Guillaume-Lachapelle requested changes
Can you add the `canActivate: [AuthguardGuard]` to the new routes you created? You can see an example here for the route for user-profile.

![image](https://github.com/amczuboka/Decagon-CondoManagementSystem/assets/92831445/467d7fc2-dccc-4b8e-a016-1772856624aa)

The rest looks good

2024-02-28 01:04 UTC, Guillaume-Lachapelle approved these changes

2024-02-28 21:58 UTC, Holyvert approved these changes

2024-02-28 22:33 UTC, merged