Individual condo page front end #101 and #115
amczuboka/Decagon-CondoManagementSystem pull request #159
Opened 2024-02-27 16:37 UTC by Tharsipa

This PR is to merge the frontend for the issues #101 and #115
Done by @CarlaShawi and @Tharsipa

2024-02-27 17:01 UTC, amczuboka approved these changes

2024-02-27 17:26 UTC, KarinaSandur approved these changes

2024-02-27 17:32 UTC, npiperni approved these changes
lgtm

2024-02-27 18:58 UTC, Ziadsharkos approved these changes

2024-02-27 19:46 UTC, PaulFarid approved these changes

2024-02-28 00:34 UTC, Guillaume-Lachapelle requested changes
Please add the AuthguardGuard to the routes for building-info and individual-condo. There is an example for user-profile here.

![image](https://github.com/amczuboka/Decagon-CondoManagementSystem/assets/92831445/667279e4-e139-47c8-b121-6c12b735edd6)

The rest looks good!

2024-02-28 01:05 UTC, Guillaume-Lachapelle approved these changes

2024-02-28 21:35 UTC, Holyvert approved these changes

2024-02-28 23:49 UTC, merged