Employees Page Front-End
amczuboka/Decagon-CondoManagementSystem pull request #160
Opened 2024-03-01 07:10 UTC by npiperni

closes #119

2024-03-01 13:55 UTC, Tharsipa approved these changes

2024-03-01 14:36 UTC, CarlaShawi approved these changes
looks good

2024-03-01 16:33 UTC, amczuboka requested changes
Overall looks great, could you change the colour of the text when the option is hovered to see it better. 
![Screenshot 2024-03-01 at 11 31 23 AM](https://github.com/amczuboka/Decagon-CondoManagementSystem/assets/94947740/bdee1146-975a-4a91-910b-c4ded746d7fa)

2024-03-01 20:48 UTC, Ziadsharkos approved these changes

2024-03-02 00:39 UTC, npiperni commented
> Overall looks great, could you change the colour of the text when the option is hovered to see it better. ![Screenshot 2024-03-01 at 11 31 23 AM](https://private-user-images.githubusercontent.com/94947740/309325869-bdee1146-975a-4a91-910b-c4ded746d7fa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkzNDAyNTUsIm5iZiI6MTcwOTMzOTk1NSwicGF0aCI6Ii85NDk0Nzc0MC8zMDkzMjU4NjktYmRlZTExNDYtOTc1YS00YTkxLTkxMGItYzRkZWQ3NDZkN2ZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzAyVDAwMzkxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU2ZTQxNjkyOGMzMzZmODcwMWI4NzZlNjNkNWI0ZmIzOTU1M2ZiNmJmYTAyMjdkNjczOTgyNTE3MzVmYzQwN2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jMGveWbnCI80grvqSIJDxMlT1wPyM7hcP8pDRu3sIFQ)

Fixed

2024-03-02 02:25 UTC, Guillaume-Lachapelle approved these changes

2024-03-02 02:25 UTC, Guillaume-Lachapelle commented on src/app/components/employees-list/employees-list.component.ts
> +  remeveSelectedItems() {
There is a typo in the name. Rename to removeSelectedItems()

2024-03-02 18:33 UTC, KarinaSandur approved these changes
Looks good!

2024-03-02 19:29 UTC, IsabelleCzuboka approved these changes
Looks good

2024-03-03 02:05 UTC, amczuboka approved these changes
Nice UI.

2024-03-04 04:08 UTC, merged