Tasks #102 #32 #33 individual condo
amczuboka/Decagon-CondoManagementSystem pull request #173
Opened 2024-03-19 01:22 UTC by CarlaShawi

This pr closes Tasks #32, #33 , #102 
- It is for fetching and displaying the proper information from the DB.
- The edit button is only available to the (building Company) and when the condo is Vacant.
- Contact information section displays owner or rented information if available. If the condo is Vacant it displays the company information. 

Done by: @Tharsipa and @CarlaShawi

2024-03-19 02:59 UTC, Guillaume-Lachapelle requested changes
In condo.component.html, right now the image of the condo is a link to the route `/individual-condo`. This isn't necessarily intuitive for users. An option would be to add a `View details` button on the condo to make it obvious for the user.

Maybe something like this under/over the button **Request for ownership**:
` <div>
                <a
                  [routerLink]="['/individual-condo', building.ID, item.ID]"
                  [queryParams]="item"
                >
                  <button class="buttonItem">View Details</button>
                </a>
              </div>`

The rest looks great!

2024-03-19 02:59 UTC, Guillaume-Lachapelle commented on src/app/pages/individual-condo/individual-condo.component.ts
> +    this.router.navigateByUrl('./condos');
Maybe use Angular's Location service to go back to the previous page. Here's how to use it:
`import { Location } from '@angular/common';`
`constructor(private location: Location) { }`

`goBack(): void {
  this.location.back();
}`

2024-03-19 15:55 UTC, Guillaume-Lachapelle approved these changes

2024-03-19 16:37 UTC, amczuboka approved these changes
Looks good. Checked for a company and public user on both available properties and my properties.

2024-03-19 23:56 UTC, npiperni approved these changes

2024-03-20 02:59 UTC, amczuboka commented
Not a huge priority, but some individual-condo's information are accessed via a button on the condo card and others are accessed by pressing the photo. At first, I didn't think we were able to access the info with the condo card without the button. Either change them all to have button or all of them not to have buttons on have a cursor: pointer for the entire condo card.

2024-03-20 04:04 UTC, Guillaume-Lachapelle commented
> Not a huge priority, but some individual-condo's information are accessed via a button on the condo card and others are accessed by pressing the photo. At first, I didn't think we were able to access the info with the condo card without the button. Either change them all to have button or all of them not to have buttons on have a cursor: pointer for the entire condo card.

Fixed!

2024-03-20 04:39 UTC, IsabelleCzuboka approved these changes
Looks great

2024-03-20 18:32 UTC, Ziadsharkos approved these changes

2024-03-21 03:25 UTC, Holyvert approved these changes

2024-03-21 03:37 UTC, merged