added the front-end for the add-new-building-operation page"
amczuboka/Decagon-CondoManagementSystem pull request #187
Opened 2024-03-21 02:09 UTC by PaulFarid

#66 

-added the front-end for the add-new-building-operation page"

2024-03-21 02:17 UTC, Guillaume-Lachapelle approved these changes

2024-03-21 02:22 UTC, IsabelleCzuboka approved these changes
Looks good to me

2024-03-21 02:53 UTC, amczuboka requested changes
The options show up in a weird spot 
![image](https://github.com/amczuboka/Decagon-CondoManagementSystem/assets/94947740/a054850d-badf-4f98-a199-c36b58bd8a2f)
. Also it would be best if there were some error handling on the inputs so that if they weren't all answered, the user can't press submit.

2024-03-21 03:24 UTC, npiperni approved these changes

2024-03-21 04:41 UTC, PaulFarid commented
> if there were some error handling on the inputs so that if they weren't all answered, the user can't press submit.

fixed  it

2024-03-21 12:37 UTC, CarlaShawi approved these changes

2024-03-21 16:10 UTC, Tharsipa approved these changes

2024-03-21 20:32 UTC, KarinaSandur approved these changes

2024-03-21 20:37 UTC, Ziadsharkos approved these changes

2024-03-21 22:32 UTC, amczuboka approved these changes

2024-03-22 01:14 UTC, Holyvert approved these changes

2024-03-22 02:12 UTC, merged