#75 cypress new building operation
amczuboka/Decagon-CondoManagementSystem pull request #205
Opened 2024-04-08 21:06 UTC by IsabelleCzuboka

This cypress test is about adding a new operation to a building. I created a function to delete an operation so that the test may run multiple times without fault.

2024-04-09 02:24 UTC, npiperni approved these changes

2024-04-09 02:48 UTC, amczuboka approved these changes
Changes look good

2024-04-09 11:15 UTC, Tharsipa approved these changes

2024-04-10 16:44 UTC, CarlaShawi approved these changes

2024-04-10 17:00 UTC, Holyvert requested changes

2024-04-10 17:00 UTC, Holyvert commented on src/app/services/building.service.ts
> +  async deleteOperationByName(buildingId: string, operationName: string): Promise<void> {
where is the unit test

2024-04-10 20:37 UTC, Guillaume-Lachapelle approved these changes
Same comment as Oliver. The rest looks good

2024-04-11 00:03 UTC, Ziadsharkos approved these changes

2024-04-12 00:57 UTC, amczuboka commented
> I think it would be better to delete the operation by ID to ensure it is unique and we don't accidentally delete an operation with the same name.

I don't think this is an issue, because it's only being used in a cypress test. If we wanted to delete it by ID, we would have to delete every operation anyway since there's no way to get the specific operation. For example, in the createBuilding.cy test it deletes every building of the user even if it only created 1 building
```     
 const promiseDelete = user.PropertyIds.map(async (ID) => {
        await(win as any).buildingService.deleteBuilding(ID);
  });
```

2024-04-12 02:06 UTC, KarinaSandur commented
> > I think it would be better to delete the operation by ID to ensure it is unique and we don't accidentally delete an operation with the same name.
> 
> I don't think this is an issue, because it's only being used in a cypress test. If we wanted to delete it by ID, we would have to delete every operation anyway since there's no way to get the specific operation. For example, in the createBuilding.cy test it deletes every building of the user even if it only created 1 building
> 
> ```
>  const promiseDelete = user.PropertyIds.map(async (ID) => {
>         await(win as any).buildingService.deleteBuilding(ID);
>   });
> ```

If that's the case, then I'll approve

2024-04-12 02:06 UTC, KarinaSandur approved these changes

2024-04-12 02:16 UTC, Holyvert approved these changes

2024-04-12 03:28 UTC, merged